### ISSUE TITLE
Sickbeard MP4 Automator 

### ISSUE THREAD

**Issue by Onyx369** [chrisanthropic/PlexInTheCloud#18]
Hey there. Assuming this is a friendly request area.
Most of us hate buffering so we convert the media to MP4 via a tool like Sickbeard MP4 Autoconvertor. That being said.... the installation of all the pre-reqs etc etc can be a real pain on a fresh install of ubuntu. 
It would be sweet if your 'all in one' scripts included an MP4 convertor like sickbeard, with a walkthrough of the autoProcess.ini pre-programed with defaults that would support Direct Play instead of Plex Server transcoding.
Thanks for the consideration and your hard work.

**Comment by chrisanthropic** [comment]
Ok, here's the deal with that - I had transcoding working via nzbToMedia PP scripts, but the resulting MP4 simply would NOT play more than 3-5 seconds without freezing for me.

That being said, I'll look into MP4_automator some more - you're right, it's a little daunting to install and configure and it seems to overlap/replace nzbToMedia.
