### ISSUE TITLE
Req - Choice of Encryption 

### ISSUE THREAD

**Issue by Onyx369** [chrisanthropic/PlexInTheCloud#21]
Feature Request:

Heh. I'm just throwing ideas at you.. feel free to ignore them if you think they are lame.

Okay on the encryption front.... it seems that we all seem to use a different model. What are the odds you could get your scripts to prompt something like
- Do you wish to use encryption? 
If no... well.... they should .. heh.... if yes... that brings them to a new set of choices
- Which encryption would you like to use EncFS or Rcrypt or Something else.

Then your scripts tailor themselves to the users choice of encryption afterwards.

I personally use EncFS as I got my start with enzTV guides and that is what he recommended at the time... now a ton of data is stored in that encryption so I have just stayed with it. 

Just a thought.

**Comment by chrisanthropic** [comment]
I'll have to think about this.
While I want to provide options, this setup is somewhat opinionated and the scripts really aren't meant to be dropped into any random system, they're meant to set-up a new system from scratch.

And rclone + crypt is super simple and much easier (for me) than EncFS.

That being said, I'm not opposed to it, but it likely won't be a priority for me so if anyone else wants to take a stab at that'll help.

**Comment by Rick7C2** [comment]
I would also like this but with the option of using google drive.

I currently use google drive without encryption.

**Comment by chrisanthropic** [comment]
I've removes support for encryption so I'm closing this.
