### ISSUE TITLE
Change default SSH port

### ISSUE THREAD

**Issue by zackbcom** [chrisanthropic/PlexInTheCloud#28]
It would be nice to offer the option to change the default ssh port. This will cut down on the hammering of the ssh port.

**Comment by Setsuneh** [comment]
You can change it with **nano** on `/etc/ssh/sshd_config`

**Comment by chrisanthropic** [comment]
Right. I'm trying to find a balance between easy to use and easy to configure.

One of the issues a LOT of this software has is the amount of configuration options. The config files are massive and a lot of the variables have shortened names which can make it hard to know WTF they do.

I have an idea to balance this but I need the time to do it.

**Comment by chrisanthropic** [comment]
I'm closing this one since fail2ban is running for port 22 and it's relatively trivial to change the port after initial installation.
