### ISSUE TITLE
Look into adding nzbToMedia to nzbget.

### ISSUE THREAD

**Issue by zackbcom** [chrisanthropic/PlexInTheCloud#32]
This will make it postprocess right when it done(Event based). Instead of waiting for cron to poll the download folder for new completed downloads.

Provides an efficient way to handle postprocessing for CouchPotatoServer and SickBeard
https://github.com/clinton-hall/nzbToMedia

**Comment by chrisanthropic** [comment]
Already done. nzbToMedia is already installed and working with Sickrage, couchpotato, and mylar.
Closing.

**Comment by zackbcom** [comment]
Perfect. I guess I missed that step.
