### ISSUE TITLE
After running 00-setup.sh port 22 refuses to connect remotely

### ISSUE THREAD

**Issue by elbasan** [chrisanthropic/PlexInTheCloud#49]
So I followed your guide but after pushing my key to the ubuntu server (digitalocean) and after the server rebotes I lose acces to port 22, i've even changed the port to 32 but it still doesn't work

> $ ssh Eli@xx.xx.xx.xx
> ssh: connect to host xx.xx.xx.xx port 22: Connection refused

**Comment by malphas12** [comment]
Check sshd conf with  sshd -t. Mine was malformed:

`UsePAM yesAddressFamily inet`

**Comment by chrisanthropic** [comment]
I still can't replicate this. Closing for now. Feel free to reopen if you can give me steps to replicate.
