### ISSUE TITLE
Can't see directories in the encrypted folder

### ISSUE THREAD

**Issue by drod3763** [chrisanthropic/PlexInTheCloud#50]
When I try to navigate to the AMZe folder there is nothing inside of it. I tried --allow_other on rclone mount and on unionfs and both of them had no effect.

`rclone lsd $encrypted:` does show the directories.

**Comment by malphas12** [comment]
I've got the same problem. I can see it all via the command line. I think I'm out of ideas now though!

**Comment by drod3763** [comment]
In some of the tutorials I have seen, it seems like you should be able to just do `ls` on the encrypted directory and see what's in there - hence the 'On the fly' decrypt. That part just doesn't seem to be working atm.

**Comment by malphas12** [comment]
Okay sorted mine. Turns out I had a typo in my AMZe remote. I had a semi colon instead of a colon. Everything was encrypting but never actually uploading.

Hopefully yours is something similar.

**Comment by Landelor** [comment]
I'm also unable to see the Movies directory in AMZe for connecting a Plex library.
