### ISSUE TITLE
Some issues I've found while trying to get this to work

### ISSUE THREAD

**Issue by TheTkeck** [chrisanthropic/PlexInTheCloud#51]
So here is a list of issues I've found in the multiple installs I've ran through:
1. NZBget doesn't have the right ownerships after installing it. Have to manually change it to my user or else the files won't download.

2. Plexmediaserver doesn't have the right permissions either. Have to change that to be able to save server settings.

3. No idea where to get the Plex token for the upload script that runs from NZBget.

4. And how does the upload script even trigger?

**Comment by chrisanthropic** [comment]
I used the scripts last week to run a fresh install and didn't see any of the issues you're reporting so let's try to narrow down any differences:

1 & 2 - What OS are you using? What VPS?

3 - I should probably add something about that to the wiki, thanks!
https://support.plex.tv/hc/en-us/articles/204059436-Finding-an-authentication-token-X-Plex-Token

4. The upload script gets triggered as a post-processing scripts by NZBget after it completes a download.

**Comment by TheTkeck** [comment]
I've attempted this multiple times and maybe I overlooked something.

1 & 2. Originally I attempted to install this on a VM I created on my personal server. The VM was running Ubuntu 16.04.2 with a clean install. The only modifications to the system was the setup of the network. After trying to run the script a couple times and running into a few different errors(one I misread and was able to fix in my later install) I switched and purchased a linode vps. I followed the steps as precisely as I could. however still came into the NZBget issue and the plexmediaserver issue. After giving owner of the plexmediaserver to the user created from the script that would work properly. NZBget was unable to create directories inside my /home/username/nzbget/completed folder. Once again after changing the ownership of the folder that was resovled.

3. I managed to find the token after some digging.

4. No matter what happened it appeared the upload script was not getting triggered. I may have not gave it enough time though. Is there any additional configuration that needs to be done with sickrage/nzbget to get the upload script functioning properly? Does autoprocessing or processing at all need to be enabled in sickrage?

**Comment by franck-boucher** [comment]
Same problem here (Ubuntu 16.04 on a dedicated machine), I can't access the Server setting to claim the server: "Server settings are unavailable".

@TheTkeck what commands did you exactly do to "give owner of the plexmediaserver to the user created from the script" ?
