### ISSUE TITLE
Can this be easily changed to use Google Drive?

### ISSUE THREAD

**Issue by stayupthetree** [chrisanthropic/PlexInTheCloud#52]
As the topic says. Would it be as easy as just changing how I setup with 'rclone config'? Or would it mess something up down the line?

**Comment by chrisanthropic** [comment]
Absolutely! I started with ACD (Amazon Cloud Drive) and currently use both on the same machine without issue.

**Comment by stayupthetree** [comment]
Do you find a performance difference between the two? Im currently using a setup involving encfs and rclone. This would eliminate the encfs portion it seems.

**Comment by chrisanthropic** [comment]
I've noticed a definite difference between the two. 

ACD is slower but more reliable. It takes longer (5-30 seconds) for a video to start. I've never had Seek (Fast-forward/rewind) or the ability to start a movie/episode from any place other than the beginning work properly.

GDrive is faster but less reliable. Videos start in 2-10 seconds. Seek, etc. works. The problem for now is how Plex indexes stuff and people have reported getting a 24-hour ban from Gdrive where they can still upload files but not download/stream. 

I personally use GDrive as a primary and if it gets banned then I fall back to ACD for a day.
